title: Omar Aymen # your name (or website title) here
logo: "/images/PNG image.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with strong math background and 4+ years of experience using predictive modeling, data processing, and data mining algorithms to solve challenging business problems
  .Involved in Python open source community and passionate about deep learning
  <br>
  <a href="https://www.linkedin.com/in/omar-ayman-6498529b/">View My LinkedIn Profile</a> 
  <br><a href="https://github.com/oaymen-ds">View My GitHub Profile</a><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
