title: Omar Aymen # your name (or website title) here
logo: "/images/PNG image.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p> 
  I am an experienced data scientist with over four years of industry expertise, currently working at TRM Labs. In my role, I leverage my skills in machine learning, problem solving, programming, and creative thinking to develop innovative AI models that analyze trends and patterns to detect fraudulent actions and suspicious behavior on the blockchain. 
I am driven by a passion for using data to solve complex problems, and I thrive in a dynamic, collaborative environment where I can apply my expertise to drive meaningful impact.
<br>
Stay in touch with me on <a href="https://medium.com/@omaraymanomar">Medium</a>, <a href="https://www.linkedin.com/in/omar-ayman-6498529b/">LinkedIn</a>, and <a href="https://github.com/omar-aymen"> GitHub </a>
<br>
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
