title: Omar Aymen # your name (or website title) here
logo: "/images/PNG image.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
   Motivated data scientist with 4+ years of experience as a data scientist. I currently work at TRM Labs, we were building AI that analyzes trends and patterns to detect fraudulent actions and suspicious behavior on the blockchain. I am passionate about building models that fix problems. Relevant skills include machine learning, problem solving, programming, and creative thinking.
  <br>
  <a href="https://www.linkedin.com/in/omar-ayman-6498529b/">View My LinkedIn Profile</a> 
  <br>   <a href="https://medium.com/@omaraymanomar">View My Medium Profile</a><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
